// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxylfinmwajovdlwzjox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eWxmaW5td2Fqb3ZkbHd6am94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDU2NTcsImV4cCI6MjA1ODk4MTY1N30.KU3nHYuipMdY2VpcPQgNQNwqVc5C-JK4P7ebWhod9bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});